obj-$(CONFIG_CLUSTER_PLUG)	:= cluster_plug.o

obj-$(CONFIG_INTELLI_PLUG)	+= intelli_plug.o
obj-$(CONFIG_MSM_SLEEPER) += msm_sleeper.o
obj-$(CONFIG_MAKO_HOTPLUG) += mako_hotplug.o
obj-$(CONFIG_ZEN_DECISION) += msm_zen_decision.o
obj-$(CONFIG_ASMP)		+= autosmp.o 
